### ISSUE TITLE
changeLogs are loosing their URIs

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.core#126]
`setChangeLog(ChangeLog changeLog)` sets the URI of the changeLog to null.
This makes sense from the TrackedResourceSet perspective, but also destroyes the changeLog, which can be used in other context when it is not a blank node. for example, when one calls http://.../.../trs/changeLog/1.
Can we instead use JMH annotations to control how the changLog is seralized, without change it?

https://github.com/eclipse/lyo.core/blob/2b5a849b0f0d0b9fe3a373b814da30b94f69c39b/oslc-trs/src/main/java/org/eclipse/lyo/core/trs/TrackedResourceSet.java#L85
 ```
public void setChangeLog(ChangeLog changeLog) throws URISyntaxException {
        // Make sure the About URI of the change log is null since it will
        // become a blank node in the turtle output
        changeLog.setAbout(null);
        this.changeLog = changeLog;
    }
```

**Comment by jadelkhoury** [comment]
@jamsden @berezovskyi I need your input on this, since you've been using these libraries recently.

**Comment by jadelkhoury** [comment]
according to the [TRS specs](https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/trs/tracked-resource-set.html#shape-trs), trs:changeLog has a valueType of "anyResource". So, a ChangeLog does not have to be a blanknode. 

So, if one sends a changeLog with a URI, it is because they don't want it to be a blankNode. that is, we should simple remove the `changeLog.setAbout(null);`

**Comment by berezovskyi** [comment]
I think #38 makes it clear that inlining must take place. We can add a new field/method level annotation like @OslcForceBNode. When serialised, we will ignore the about URI and create a blank node.

**Comment by berezovskyi** [comment]
As a workaround we can also clone the log first.

**Comment by jadelkhoury** [comment]
Inlining is not a problem. And that is still the case. But Inlining is different from making it a blank node. One can online a normal resource. 

My suggestion is to simply remove the line 

`changeLog.setAbout(null);`

**Comment by berezovskyi** [comment]
Right, got it. While legally correct move according to the spec, JMH will not unmarshall inlined resources that _are not_ blank nodes in OSLC fields. Maybe that's the thing we should fix.

**Comment by berezovskyi** [comment]
Let's make the change you propose and roll it back if it crashes stuff.

**Comment by jadelkhoury** [comment]
upon further investigation, it seems reasonable for the changeLog's URI to be set to null. 
A changeLog inside a TrackedResourceSet should be a local resource.
It is only paged ChangeLogs that have a URI. but then such instances ought not be part of a TrackedResourceSet.

So, this is not a bug, and we can close this issue.

Alternatively, `setChangeLog(ChangeLog changeLog)` should raise an exception if the changeLog has a URI, instead of changing it.
