### ISSUE TITLE
Create an update site and plugins out of the Lyo libraries

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.core#128]
Sometimes one needs to include a Lyo library (core, client, trs) as Eclipse plugins. provide an update site for people to download such plugins.

There has been a number of pull requests (attempts) at this, but here is an issue to collect some ideas.
* https://github.com/eclipse/lyo.core/pull/62 in Core
* https://github.com/eclipse/lyo.core/issues/35 in Core
* https://github.com/eclipse/lyo.core/pull/62 in Core
* https://github.com/eclipse/lyo.designer/issues/41 in LyoDesigner

**Comment by jadelkhoury** [comment]
And here is a thread that might give some insights.

From: <tycho-user-bounces@eclipse.org> on behalf of Bart van Leeuwen <bart@netage.nl>
Reply to: Tycho user list <tycho-user@eclipse.org>
Date: Wednesday, 13 November 2019, W46 at 19:21
To: Tycho user list <tycho-user@eclipse.org>
Subject: Re: [tycho-user] Plugin builds with Tycho but cannot find imports in eclipse

Hi, 

first of all thank you for the quick and elaborate responses! 

Used a hybrid of the 2 mails to get this working, I've now created way to have both Eclipse and Maven work as expected. 
The only 'issue' is that for the dependencies I needed to create a seperate update site to have the be able to install the plugin created with tycho 

The project created through step 3 of this tutorial makes the eclipse environment work flawlessly! 
https://www.vogella.com/tutorials/EclipseJarToPlugin/article.html 

but to get the tycho build installing I had to create a updatesite around that project and host it on a external server. 
It would be great if the project would be included in the repository created through tycho-repository step. 

Any hints appreciated 

Met Vriendelijke Groet / With Kind Regards
Bart van Leeuwen 



From:        Dirk Fauth <dirk.fauth@googlemail.com> 
To:        Tycho user list <tycho-user@eclipse.org> 
Date:        13-11-2019 12:29 
Subject:        Re: [tycho-user] Plugin builds with Tycho but cannot find imports        in eclipse 
Sent by:        tycho-user-bounces@eclipse.org 
________________________________________



Depending on how many jars there are you could also create the plugins from jars as explained here: https://www.vogella.com/tutorials/EclipseJarToPlugin/article.html 

Or if you want to stick with plain maven switch to bndtools.  

Johan Compagner <jcompagner@servoy.com> schrieb am Mi., 13. Nov. 2019, 12:08: 
What i would do is really build your own p2 site for those 3th party dependencies 
And then in you target platform include that one  
So these are all plain plugin dependencies (so not in the maven pom file) 

First check orbit (if those 3th party are not already there) 

https://download.eclipse.org/tools/orbit/downloads/drops/R20190827152740/  

i do the same thing.. 

this is a eclipse project: 

https://github.com/Servoy/servoy-eclipse/tree/master/shipplugins  

that has a pom and category.xml file that generates our p2 site of 3th party plugins that i need as a p2 site.. 

our target file that we have in eclipse just references that p2 site that the above link generates: 

https://github.com/Servoy/servoy-eclipse/blob/master/launch_targets/eclipse.target#L40 

  
  

On Wed, 13 Nov 2019 at 09:42, Bart van Leeuwen <bart@netage.nl> wrote: 
Hi, 

I've used this method to create OSGI bundle jar from the dependencies 
https://flames-of-code.netlify.com/blog/maven-and-tycho-deps/ 

The actualy project for the dependcies can be found here: 
https://github.com/nicky508/dependency_bundle 

its installed in my local .m2 repository, referenced as a dependency in the parent pom.xml and referenced in the manifest.mf file of the module that needs the dependencies. 

Mind you this work with maven tycho build, Eclipse does not seem to understand it. 

Met Vriendelijke Groet / With Kind Regards
Bart van Leeuwen 




From:        Johan Compagner <jcompagner@servoy.com> 
To:        Tycho user list <tycho-user@eclipse.org> 
Date:        13-11-2019 08:30 
Subject:        Re: [tycho-user] Plugin builds with Tycho but cannot find imports        in eclipse 
Sent by:        tycho-user-bounces@eclipse.org 


Are those external libs really osgi bundle? 
Because in the end they need to be plugin that is bundled with your feature/product.. 

Under what container are they visible in the package explorer? 

If they are under plugin dependencies then maybe your feature needs to include them as dependencies as well (not 100% sure that is really needed but they need to ship with it) 

Op di 12 nov. 2019 22:08 schreef Bart van Leeuwen <bart@netage.nl>: 
Hi, 

We are developing a plugin and use maven and tycho for the build process. 
This works fine up to the point that we started using external libraries. 
We created a project which contains all the external dependencies and reference that in the manifest. 

We can now build with maven and tycho and it works as expected, 

In the eclipse development environment however the external dependencies are not resolved and cause error indicators in the Java editors. 
I've searched for a couple of hours and looked at various options, but I'm now in the blue, any help is appreciated.

**Comment by berezovskyi** [comment]
http://download.eclipse.org/lyo/bundle/p2/stable/?d
