### ISSUE TITLE
isWriteable() check prevents from return an array of *different* RDF resources

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.core#21]
`org.eclipse.lyo.oslc4j.provider.jena.AbstractOslcRdfXmlProvider#isWriteable` has the logic that checks the underlying type of the array for the OSLC annotations on the base class:

```
		if (type.getAnnotation(OslcResourceShape.class) != null ||
			type.getAnnotation(OslcNotQueryResult.class) != null)
		{
			// We do not have annotations when running from the non-web client.
			if (isCompatible(actualMediaType, requiredMediaTypes))
			{
				return true;
			}
		}
```

This is bad for 2 reasons:

1. It behaves differently under an OSLC Server (adaptor) and a standalone OSLC Client.
1. Its "smartness" will only work when, for example, a `Requirement[]` is returned where a method returns `Object[]`.

In my case, I hit the second problem because I was truly returning an `Object[]` with an instance of one valid OSLC resource class instance in `[0]` and another (different) valid OSLC resource class instance in `[1]`.

**Comment by berezovskyi** [comment]
I suggest to simply return `true` always and rely on JAX-RS `@Produces` annotations and generic type arguments like `MessageBodyWriter<Object[]>` to select the appropriate provider.

**Comment by berezovskyi** [comment]
If we want to do a _real_ check, we can only do it inside `org.eclipse.lyo.oslc4j.provider.jena.OslcRdfXmlArrayProvider#writeTo` after looping over the contents of the array and checking the annotations on the classes of each instance.

**Comment by berezovskyi** [comment]
@jadelkhoury @jamsden @yashkhatri will you accept a PR where I just return true?

P.S. Already verified on my OSLC servers.

**Comment by berezovskyi** [comment]
@jamsden @jadelkhoury I would like to review this change for 2.4.0

**Comment by jadelkhoury** [comment]
If isWritable() simply returns true, would'nt this provider simply accept all requests? Given that we have a number of such Providers, I thought we do need different logic to decide which provider to choose. (Besides the mediaType which seems to be filtered through the annotations).

I am mainly thinking of the other Provider OslcRdfXmlCollectionProvider, that is meant to deal with Collections.

Now, for your particular scenarion, is Requirement[] meant to be a response to a Query? If not, did you test with this "OslcNotQueryResult" annotation? I have not used it myself, but I wonder if its meant to be used when one wants to return an Collection, yet it is not part of a QueryResult.

Otherwise, given that you are dealing with collections/arrays, shouldn't the fix be in OslcRdfXmlCollectionProvider?

**Comment by berezovskyi** [comment]
For example, I want to return a Requirement and a ChangeRequest. Both of them have the right annotations and will be correctly processed by JMH but I can only return them together as an Object[]. And the Object does not have any OSLC annotations.

True, I can fix that in every collection provider but the reason for fixing it here is that I want to make sure this behaviour is the same on the client as on the server. Did not test on the client though.

Also, do we have any docs for the "not a query" annotation?

--
/Andrew

On 12 Nov 2018, at 09:32, Jad El-khoury <notifications@github.com<mailto:notifications@github.com>> wrote:


If isWritable() simply returns true, would'nt this provider simply accept all requests? Given that we have a number of such Providers, I thought we do need different logic to decide which provider to choose. (Besides the mediaType which seems to be filtered through the annotations).

I am mainly thinking of the other Provider OslcRdfXmlCollectionProvider, that is meant to deal with Collections.

Now, for your particular scenarion, is Requirement[] meant to be a response to a Query? If not, did you test with this "OslcNotQueryResult" annotation? I have not used it myself, but I wonder if its meant to be used when one wants to return an Collection, yet it is not part of a QueryResult.

Otherwise, given that you are dealing with collections/arrays, shouldn't the fix be in OslcRdfXmlCollectionProvider?

**Comment by jadelkhoury** [comment]
@berezovskyi and @jadelkhoury did a review. Agree that it is reasonable for isWritable() to simply return true. But this should also apply to all other providers, such as OslcRdfXmlCollectionProvider.

Make this change as part of 4.0

**Comment by berezovskyi** [comment]
should do this with https://github.com/eclipse/lyo.core/pull/9/files

**Comment by berezovskyi** [comment]
for my future self: `sandbox.whc.WarehouseControllerManager#getPlan`
