### ISSUE TITLE
the oslc4j.bundle pom configuration is missing the version

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.core#35]
Comparing to other plugin projects under LyoDesigner, it seems that oslc4j-bundle does not specify its version. Could this be the reason I have had some issues using this bundle - sometimes? 

That is, the pom.xml file should be 

```
  <artifactId>oslc4j-bundle</artifactId>
  <name>${bundle.symbolicName}</name>
  <version>2.4.0-SNAPSHOT</version> <!-- This version should match the version of your project in the MANIFEST.MF -->
  <packaging>bundle</packaging>

```

**Comment by jadelkhoury** [comment]
@berezovskyi ! @yashkhatri and I suspect this is needed, but maybe you can shed more light on how to configure these pom files?

**Comment by yashkhatri** [comment]
@jadelkhoury We have specified parent tag in the [POM](https://github.com/eclipse/lyo.core/blob/5293b49c10eee6d8c34c73b84a91b0058d2620c9/oslc4j-bundle/pom.xml#L6) Hence, it's not necessary to specify the version if we want to keep it same as parent pom's version. In this case [oslc4j-core-build](https://github.com/eclipse/lyo.core/blob/5293b49c10eee6d8c34c73b84a91b0058d2620c9/org.eclipse.lyo.oslc4j.build/pom.xml#L6) project.

[source](https://stackoverflow.com/questions/12315746/what-will-the-version-be-when-i-dont-specify-it-in-the-mavens-pom-xml)

**Comment by jadelkhoury** [comment]
Agree. @yash. 
Did you see my other branch from today where I am trying to create an update-site for the bundle?

**Comment by yashkhatri** [comment]
@jadelkhoury Yes. I had a quick look. I will comment over there.

**Comment by berezovskyi** [comment]
agree with Yash, closing.
