### ISSUE TITLE
OslcJsonLdProvider never called when trying to write to 'application/ld+json' 

### ISSUE THREAD

**Issue by cedric780** [eclipse/lyo.core#44]
Writing to `'application/ld+json'` MIME type never work , [OslcJsonLdProvider](https://github.com/eclipse/lyo.core/blob/71099a1db5ced4d229246908aa7a85fc47de8bd5/oslc4j-jena-provider/src/main/java/org/eclipse/lyo/oslc4j/provider/jena/OslcJsonLdProvider.java) is never called.
Probably same problem for `OslcJsonLdCollectionProvider` and `OslcJsonLdArrayProvider`.

    
#### Cause:

OslcRdfXmlProvider.isWriteable(Class<?>, Type, Annotation[], MediaType)  in the parent `OslcRdfXmlProvider` class hard codes accepted media types when calling static isWriteable(...)

https://github.com/eclipse/lyo.core/blob/71099a1db5ced4d229246908aa7a85fc47de8bd5/oslc4j-jena-provider/src/main/java/org/eclipse/lyo/oslc4j/provider/jena/OslcRdfXmlProvider.java#L139-L145

**Comment by jadelkhoury** [comment]
Indeed. I can confirm that json-ld is not handled in the most basic cases.
@berezovskyi I can dig into this. 
but, to get started, was it you that introduced jsonld? can't seem to find the original patch that introduced jsonLd.

**Comment by berezovskyi** [comment]
hahaha, @jadelkhoury I have never hit this bug because I had #22 applied from the start in my case.

**Comment by jadelkhoury** [comment]
Until we have #22 in place, can we fix this? if you give me a rundown on what [damage :-)] you did, I can try to fix it in comming days.

**Comment by berezovskyi** [comment]
@cedric780 thanks for reporting the bug and getting to the cause of it

@jadelkhoury I still believe #22 is the best fix for it, now we have 2 reasons to apply it. @jamsden Jad is worried about accidentally introducing an unwanted side effect that may introduce some incompat.

**Comment by jadelkhoury** [comment]
I am mainly worried about introducing such a change just before the 2.4.0 release. If we add #22 after the release, it gives us a better chance to run it for some time.

**Comment by berezovskyi** [comment]
@jadelkhoury it's not really that I did something [damage], but I just forgot to add a new argument to the inner `isWriteable` call. If you add `OslcMediaType.APPLICATION_JSON_LD_TYPE` to the end of the call, things should work back again.

BTW, @cedric780 I am trying to introduce #9 which adds support for N-Triples and any other serialisation format as supported by Jena but there has been little push for it. If you are interested to try it out, I can help you with any issues that may arise in the process.

**Comment by berezovskyi** [comment]
@cedric780 please try the fix in #45
