### ISSUE TITLE
Wrong annotations on the ServiceProvider class

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.core#64]
This is a partial stacktrace when I try to unmarshall a collection of ServiceProvider instances from the triplestore (via Lyo Store):

```
org.eclipse.lyo.store.ModelUnmarshallingException: org.eclipse.lyo.oslc4j.core.exception.OslcCoreMisusedOccursException:
OSLC012: Multiple values for method setCreated of class org.eclipse.lyo.oslc4j.core.model.ServiceProvider 
that supports at most one value
	at org.eclipse.lyo.store.internals.SparqlStoreImpl.getResourcesFromModel(SparqlStoreImpl.java:365)
```

**Comment by berezovskyi** [comment]
cc @jamsden @jadelkhoury

**Comment by berezovskyi** [comment]
I will investigate. This is really strange b/c the getCreated returns a single Date anyway. I suspect the `about` setter is not called properly and it creates a subsequent mess in the persisted graph.

**Comment by berezovskyi** [comment]
Got it. The error is triggered by me trying to add the same SP to a Set multiple times:

```java
@Override
public void addServiceProvider(final ServiceProvider sp) {
    final Collection<ServiceProvider> serviceProviders = getServiceProviders();
    serviceProviders.add(sp);
    try {
        store.putResources(twinsGraphURI, serviceProviders);
    } catch (StoreAccessException e) {
        throw new IllegalStateException("Unable to persist the new SP in the KB");
    }
}
```

I was expecting the Set implementation to catch that but the problem is that it relies on `equals` and `hashCode` implementations. This brings us back to an old question. I wanted for a long time to define the `equals` and `hashCode` just in terms of the `about` URI. I think both @jadelkhoury and @jamsden were uneasy about ignoring all other properties.

I think it makes sense to expect the check 

    if(serviceProviders.contains(sp)) {
        
    }

to return true if a Set already contains a resource with the same URI. If we don't agree to add such equality implementations, I would have to reimplement my `Set` as a `Map<URI, SP>` and then do a check on the about URIs. I am not sure if that's the better way or just a hack.

**Comment by berezovskyi** [comment]
Got it. The error is triggered by me trying to add the same SP to a Set multiple times:

```java
@Override
public void addServiceProvider(final ServiceProvider sp) {
    final Collection<ServiceProvider> serviceProviders = getServiceProviders();
    serviceProviders.add(sp);
    try {
        store.putResources(twinsGraphURI, serviceProviders);
    } catch (StoreAccessException e) {
        throw new IllegalStateException("Unable to persist the new SP in the KB");
    }
}
```

I was expecting the Set implementation to catch that but the problem is that it relies on `equals` and `hashCode` implementations. This brings us back to an old question. I wanted for a long time to define the `equals` and `hashCode` just in terms of the `about` URI. I think both @jadelkhoury and @jamsden were uneasy about ignoring all other properties.

I think it makes sense to expect the check 

    if(serviceProviders.contains(sp)) {
        
    }

to return true if a Set already contains a resource with the same URI. If we don't agree to add such equality implementations, I would have to reimplement my `Set` as a `Map<URI, SP>` and then do a check on the about URIs. I am not sure if that's the better way or just a hack. The Map would also make it harder to work with the collections returned by Lyo Store.

**Comment by berezovskyi** [comment]
An about URI in this case is a perfect example of a Natural identifier as explained here: https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/

**Comment by berezovskyi** [comment]
@jadelkhoury @jamsden @yashkhatri what's your opinion?

**Comment by jadelkhoury** [comment]
I think it makes sense to define equal in terms of the about URI.

**Comment by neormx** [comment]
I definitely agree, AbstractResource should implements equals and hashcode based on the about URI. Sometimes I had have to implement my own Comparator in order to keep unique resources into a Set... I suggest to modify Link class also to implement equals and hashcode in terms of the value property.

**Comment by berezovskyi** [comment]
Nothing wrong with the annotations on the ServiceProvider class, closing.

Equality checking will be handled in #82.
