### ISSUE TITLE
AbstractOslcRdfXmlProvider.getSerializtionLanguage() doesn't recognize MediaType.TEXT_XML

### ISSUE THREAD

**Issue by jamsden** [eclipse/lyo.core#85]
RTC responds to a request to read a ServiceProvider with text/xml. OslcClient can't read this because AbstractOslcRdfXmlProvider.getSerializtionLanguage() doesn't recognize MediaType.TEXT_XML
Adding:
```
		mediaPairs.add(new AbstractMap.SimpleEntry<>(OslcMediaType.TEXT_XML_TYPE,
				 RDFLanguages.strLangRDFXML));
```
fixes it, but I don't know why this might have been removed, or what might have changed in RTC so that it is returning text/xml instead of application/rdf+xml.

[Providers rely on annotation inheritance in JAX-RS](
https://github.com/eclipse/lyo.core/issues/67) - this resulted from a difference in how Wink vs Jersey handle annotation inheritance. Andrew will fix this.

**Comment by berezovskyi** [comment]
Will take a look. I think we discussed this before and there is a subclass of the Abstract provider called Text-something or Plain-something and that's the one that handles such MIME types perfectly.

--
–Andrew.

2019-03-18  kl. 17:05 skrev Jim Amsden <notifications@github.com<mailto:notifications@github.com>>:


Assigned #85<https://github.com/eclipse/lyo.core/issues/85> to @berezovskyi<https://github.com/berezovskyi>.

**Comment by berezovskyi** [comment]
Jim, you are right, we need this line. Please submit a PR and I will review.
