### ISSUE TITLE
Move JenaModelException to Core

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.core#87]
We have an exception under https://github.com/eclipse/lyo.trs-client/blob/master/src/main/java/org/eclipse/lyo/oslc4j/trs/client/exceptions/JenaModelException.java

But it would be useful to combine all kinds of Jena-caused exceptions in the Core in a similar way.

I would suggest to move the exception to Core?

**Comment by berezovskyi** [comment]
@jadelkhoury @jamsden what do you think?

**Comment by jamsden** [comment]
I don't think its necessary to organize all exceptions in one place. Rather it might be better to organize specific exceptions with the functions they guard. If JenaModelException has anything in it that deals with client exceptions, then it should stay where it is. Also moving it would be API breaking because the package and dependencies would change. Doesn't seem worth it.

**Comment by berezovskyi** [comment]
Jim, I am not talking about wrapping all exceptions in one. I.e. this is not some mega `LyoException`. But please look at https://github.com/eclipse/lyo.core/blob/master/oslc4j-jena-provider/src/main/java/org/eclipse/lyo/oslc4j/provider/jena/JenaModelHelper.java#L109

Do you want to honestly tell me that every Lyo user carefully processes each exception separately?! I want to be able to change the signature of that method to:

```java
public Model createJenaModel(final Collection<IResource> objects)
		   throws JenaModelException, OslcCoreApplicationException
```

Of course, that will be in a separate class (that will not be static, cough). So, no compat is expected to be broken (but we will `@Deprecate` the JMH static methods accordingly). 

And this gives me a way to nicely handle the exceptions:

- catch JenaModelException: "Error creating a Jena model from the Objects, cause: %inner exception%
- catch OslcCoreApplicationException: "Resources have invalid OSLC annotations, cause: %message%"

And I plan to rethrow `IllegalAccessException` as an unchecked exception.

If you have a better idea, please tell me! cc @yashkhatri @neormx

**Comment by jamsden** [comment]
I was referring to organizing exceptions in one package or module, not using one exception.

**Comment by berezovskyi** [comment]
Ah, I see. Thank you, sorry for the misunderstanding. Then, I still think that particular exception needs to be moved. Otherwise we will risk a circular dependency when Core depends on TRS for a `JenaModelException` while TRS depends on Core for the JMH and other things.

**Comment by jadelkhoury** [comment]
So this is about the specific exception JenaModelException and not a general approach to consolidate all exemptions. 

Makes sense to have this exception where Jena is handled. Hence Core makes sense, which is itself used by most other modules.
At least, not Lyo.trs-Client.

**Comment by yashkhatri** [comment]
I agree. JenaModelException should be in the same project as JenaModelHelper. Hence, it makes sense for me as well to move it to core.

**Comment by berezovskyi** [comment]
Fresh from the new Lyo Client:

![image](https://user-images.githubusercontent.com/64734/56504317-6f27a380-6518-11e9-8b01-d38c7f36897c.png)

- full exceptions shall be wrapped, so that the handler can inspect the previous exception, not just read its message
- OslcCoreApplicationException shall not be wrapped but declared as a checked exception
- all other exceptions shall be either wrapped into OslcCoreApplicationException or JenaModelException
