### ISSUE TITLE
Removing all logic from AbstractOslcRdfXmlProvider::isWritable causes wrong JAX-RS Provider to handle arrays

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.core#96]
The commit 
https://github.com/eclipse/lyo.core/commit/adad0119449af8d5c5c9b737fe02930b2310b5e8 removes all logic from isWritable. 

But one should not  return true, when the "type" parameter is an array!
 
When the response is a query response  (array), simply returning true, leads to the wrong OslcRdfXmlProvider Provider being called, instead of the expected OslcRdfXmlArrayProvider.
 
This causes JenaModelHelper to fail since it is not implemented to handle such a scenario.
Where it currently fails is in JenaModelHelper::recursivelyCollectNamespaceMappings, since the resourceClass parameter is an array instead of being a single object. This leads to the call "resourceClass.getPackage()" to return null, and hence cause an exception.

If we want isWritable  to be true in this abstract class, then we need to change the logic in the OslcRdfXmlProvider::isWritable method to make sure it returns false upon an array parameter.
What about all other classes that specialize this abstract class?

**Comment by berezovskyi** [comment]
Thanks for the report. Looking into thi.

**Comment by jadelkhoury** [comment]
To reproduce, start the sample rm adaptor, branch 4.0.0-snapshot and perform an oslc query request with accept rdf+xml
